server:
  port: 8080

spring:
  application:
    name: ttcs-app
  datasource:
    url: jdbc:postgresql://localhost:5432/ttcs
    username: duke
    password: duke
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: a8e33b4cd23905e1cfdac93858f74db34770b55e2bcb95a7d70563fd54c16b0b


application:
  security:
    jwt:
      secret-key: 5e1cfdac9385a770b557058e33b4cd2390e2bcb95a7d8f74db3463fd54c16b0b
      expiration: 86400000
  ai:
    lstm:
      model-path: ./models/behavioral_lstm.zip
    groq:
      api-key: YOUR_API_KEY
      model-name: llama-3.3-70b-versatile

#     