server:
  port: 8080

spring:
  application:
    name: ttcs-app
  datasource:
    url: jdbc:postgresql://localhost:5432/ttcs
    username: duke
    password: duke
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret: a8e33b4cd23905e1cfdac93858f74db34770b55e2bcb95a7d70563fd54c16b0b

aws:
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}
